/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.ArbolBinario;
import Clases.Archivos;
import Clases.Multilistas;
import Clases.Nodo;
import Clases.NodoArbol;
import Clases.Propiedades;
import Clases.TablasHash;
import static Vistas.VtnGrupo.arr;
import static Vistas.VtnGrupo.r;
import cjb.ci.Mensaje;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author zgame
 */
public class VtnContacto extends javax.swing.JFrame {

    public String d; // DATO A BUSCAR
    public Nodo r1; //RAIZ DE LA MULTILISTA

    /**
     * Creates new form VtnContacto
     */
    public void transparenciaBotones() 
    {
        jBRegresarC.setContentAreaFilled(false);
        jBAgregarC.setContentAreaFilled(false);
        jBEliminarC.setContentAreaFilled(false);
        jBMoverC.setContentAreaFilled(false);
        jBAsistente.setContentAreaFilled(false);

    }

    public boolean valida(String s) {
        boolean valida = false;
        for (int i = 0; i < s.length(); i++) {
            char caracter = s.toUpperCase().charAt(i);
            int valorASCII = (int) caracter;
            if (valorASCII > 64 && valorASCII < 91) {
                valida = true;
                //return false; //Se ha encontrado un caracter que no es letra 
            }
            if (valorASCII > 97 && valorASCII < 123) {
                valida = true;
                //return false; //Se ha encontrado un caracter que no es letra 
            }

        }

        System.out.println("VALOR DE VALIDA:" + valida);

        boolean validatodo = false;

        if (s.length() == 0) {
            Mensaje.error(this, "Campo vacio, debe ingresar un nombre primero");
            validatodo = false;
        } else {
            if (valida == false) {
                 Mensaje.error(this, "Error, caracter invalido detectado\n Los caracteres permitidos para este apartado son solo letras");
                validatodo = false;
            } else {
                validatodo = true;
            }
        }

        System.out.println("VALIDA TODO;" + validatodo);
        return validatodo;
    }

    public static boolean validaC(Nodo r, String etq)//valida que el nombre de un grupo no se repita 
    {
        boolean aux = false;
        while (r != null) {
            if (r.getEtq().equalsIgnoreCase(etq.trim())) {
                aux = true;
                break;
            } else {
                r = r.getSig();
            }
        }
        System.out.println("EL DATO QUE ENCONTRE FUE:" + aux);
        return aux;
    }
    
    public static boolean validaN(String etq)//valida que no haya un nombre igual en dos grupos distintos
    {
        boolean aux = false;
        while (r != null) {
            if (r.getEtq().equalsIgnoreCase(etq.trim())) 
            {
                aux = true;
                break;
            } else 
            {
                r = r.getSig();
            }
        }
        if (aux==false) 
        {
            r=r.getAbj();
            while (r != null) 
            {
                if (r.getEtq().equalsIgnoreCase(etq.trim())) 
                {
                    aux = true;
                    break;
                } else {
                    r = r.getSig();
                }
            }  
        }
        
        
        return aux;
    }
    

    public VtnContacto() {
        initComponents();
        this.setLocationRelativeTo(null); //CENTRA LA PANTALLA

        jLContactos.setForeground(Color.WHITE); //PONE EL COLOR DE LA ETIQUETA EN BLANCO
        JPContactos.setBackground(Color.WHITE);//PONE BLANCO EL COLOR DEL PANEL

        JPContactos.setLayout(new BoxLayout(JPContactos, BoxLayout.PAGE_AXIS));//CAMBIA EL ESTILO DE EL PANEL, PERMITE QUE LOS BOTONES NO OCUPEN TODA LA PANTALLA

        transparenciaBotones();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLContactos = new javax.swing.JLabel();
        jBAgregarC = new javax.swing.JButton();
        jBEliminarC = new javax.swing.JButton();
        jBRegresarC = new javax.swing.JButton();
        jBMoverC = new javax.swing.JButton();
        jLEliminarC = new javax.swing.JLabel();
        jLMoverC = new javax.swing.JLabel();
        jLAgregarC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPContactos = new javax.swing.JPanel();
        jBAsistente = new javax.swing.JButton();
        jLFondoC = new javax.swing.JLabel();
        jLFondoC1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLContactos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLContactos.setText("Contactos");
        getContentPane().add(jLContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jBAgregarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarCNuevo.png"))); // NOI18N
        jBAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarCActionPerformed(evt);
            }
        });
        getContentPane().add(jBAgregarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 57, -1));

        jBEliminarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrarNuevo.png"))); // NOI18N
        jBEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarCActionPerformed(evt);
            }
        });
        getContentPane().add(jBEliminarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 56, -1));

        jBRegresarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atrasNuevo.png"))); // NOI18N
        jBRegresarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarCActionPerformed(evt);
            }
        });
        getContentPane().add(jBRegresarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 30));

        jBMoverC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/moverNuevo1.png"))); // NOI18N
        jBMoverC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMoverCActionPerformed(evt);
            }
        });
        getContentPane().add(jBMoverC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 55, -1));

        jLEliminarC.setText("Eliminar");
        getContentPane().add(jLEliminarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jLMoverC.setText("Mover");
        getContentPane().add(jLMoverC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        jLAgregarC.setText("Agregar");
        getContentPane().add(jLAgregarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        JPContactos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPContactos.setLayout(new java.awt.GridLayout(0, 1, 0, 1));
        jScrollPane1.setViewportView(JPContactos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 290, 360));

        jBAsistente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevoPregunta25.png"))); // NOI18N
        jBAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsistenteActionPerformed(evt);
            }
        });
        getContentPane().add(jBAsistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 30, -1));

        jLFondoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondowhats.png"))); // NOI18N
        getContentPane().add(jLFondoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLFondoC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondowa2.jpg"))); // NOI18N
        getContentPane().add(jLFondoC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarCActionPerformed

        String s = "";

        s = JOptionPane.showInputDialog("Escriba el nombre del contacto que desea agregar");

        if (s == null) {
            //Evita el NPE al salir del showInputDialog o presionar cancelar
        } else if (valida(s) == false) {
            System.out.println("error");//cambiar por un mensaje de error
        } else {
            if (validaC(r1, s) == true) {
                Mensaje.error(this, "El nombre que desea ingresar se encuentra repetido, por favor ingrese uno diferente");
            } else 
            {

                 if (s.length()>30) 
                {
                    Mensaje.error(this, "El nombre que intenta ingresar excede el numero de caracteres permitido(30)");
                }
                else
                {
                    VtnGrupo c = new VtnGrupo();
                    if (c.validaN(s)==true) 
                    {
                        Mensaje.error(this,"El nombre que desea ingresar se encuentra ya en otro grupo");
                    }
                    else
                    {
                        Nodo con = new Nodo(null, s.trim());
                        String[] etqs = new String[2];
                        etqs[0] = d;//toma el texto del boton que se eligio anteriorente
                        etqs[1] = s;

                        NodoArbol nomNAS = new NodoArbol(s.trim(), null, etqs);

                        VtnGrupo.r = Multilistas.inserta(VtnGrupo.r, con, 0, etqs); //inserta Multilista

                        VtnGrupo.arr.insertaTH(s, nomNAS);//inserta arbol

                        Propiedades p = new Propiedades(VtnGrupo.r, VtnGrupo.arr);

                        try {
                            Archivos.guardar(p, this);
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(VtnW.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        r1 = Multilistas.busca(VtnGrupo.r, d); //buscar en donde vas a insertar
                        r1 = r1.getAbj();//si
                        JPContactos.removeAll();

                        if (r1 != null) {
                            Nodo aux = r1;
                            while (aux != null) {
                                JButton boton = new JButton(aux.getEtq());

                                //boton.setLocation(50, 10);
                                boton.setBackground(Color.WHITE);//PONE EL FONDO DEL BOTON EN BLANCO
                                boton.setForeground(Color.BLACK);//PONE LAS LETRAS COLOR NEGRO
                                boton.setFont(new Font("arial", 1, 14));//CAMBIA LA FUENTE Y EL TAMAÑO

                                //ESTABLECE UN TAMAÑO POR DEFECTO PARA LOS BOTONES
                                boton.setMinimumSize(new Dimension(JPContactos.getWidth(), 50));
                                boton.setMaximumSize(new Dimension(JPContactos.getWidth(), 50));
                                boton.setPreferredSize(new Dimension(JPContactos.getWidth(), 50));

                                JPContactos.add(boton);
                                boton.addActionListener(new ActionListener() {
                                    @Override
                                    public void actionPerformed(ActionEvent e) {
                                        VtnHistorial h = new VtnHistorial();
                                        h.d1 = d;
                                        h.d2 = boton.getText();
                                        h.setVisible(true);
                                    }
                                }
                                );
                                aux = aux.getSig();
                            }
                        }
                    }//FIN DEL VALIDA QUE UN NOMBRE ESTE EN OTROS GRUPOS
                }//FIN DEL ESLE DE VALIDA 30 CARACTERES
            }
            JPContactos.revalidate();
            JPContactos.repaint();
        }
    }//GEN-LAST:event_jBAgregarCActionPerformed

    private void jBMoverCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMoverCActionPerformed

        Nodo rm;
        String nom = ""; //nom=NOMBRE A BUSCAR
        String gpo = "";

        boolean b1 = true;
        boolean b2 = true;

        nom = JOptionPane.showInputDialog("Escriba el contacto que desea mover");

        if (nom == null) {
            b1 = false;
            //Evita el NPE al salir del showInputDialog o presionar cancelar
        } else if (valida(nom) != false) {
            gpo = JOptionPane.showInputDialog("Escriba el grupo al que desea mover este contacto");
            if (gpo != null) {
                b2 = false;
                //Evita el NPE al salir del showInputDialog o presionar cancelar
                if (validaC(r, gpo) == false)//significa que no encontro nada 
                {
                    Mensaje.error(this, "El grupo al cual desea mover el contacto no se encontro");
                } else {

                    if (gpo.length() == 0) {
                        Mensaje.error(this, "Los campos no deben estar vacios");
                    }
                    if (b1 == false && b2 == false) {

                    } else if (nom.length() != 0 && gpo.length() != 0) {
                        rm = Multilistas.busca(VtnGrupo.r, gpo);
                        rm = rm.getAbj();

                        if (rm != null) {
                            if (validaC(rm, nom) == true) {
                                Mensaje.error(this, "El nombre que intentas ingresar esta repetido en grupo " + gpo);
                            } else {
                                String[] etqsE = new String[2];
                                etqsE[0] = d;
                                etqsE[1] = nom;

                                String[] etqsI = new String[2];
                                etqsI[0] = gpo;
                                etqsI[1] = nom;

                                VtnGrupo.r = Multilistas.mover(VtnGrupo.r, 0, etqsE, etqsI);

                                int pos = nom.toUpperCase().codePointAt(0) - 65;

                                if (VtnGrupo.arr.getArr()[pos] != null) {

                                    ArbolBinario aba = new ArbolBinario();

                                    NodoArbol aux = aba.busca(VtnGrupo.arr.getArr()[pos].getR(), nom);

                                    if (aux != null) {

                                        aux.setPredecesores(etqsI);

                                        Propiedades p = new Propiedades(VtnGrupo.r, VtnGrupo.arr);
                                        try {
                                            Archivos.guardar(p, this);
                                        } catch (FileNotFoundException ex) {
                                            System.out.println(" No se encontro el archivo ");
                                        }
                                    }
                                }
                                r1 = Multilistas.busca(VtnGrupo.r, d);
                                r1 = r1.getAbj();

                                if (r1 != null) {
                                    Component componentes[] = JPContactos.getComponents();

                                    for (int i = 0; i < componentes.length; i++) {
                                        System.out.println(((JButton) componentes[i]).getText());
                                        if (etqsE[1].equals(((JButton) componentes[i]).getText().trim())) {
                                            JPContactos.remove(i);
                                        }
                                    }

                                } else {
                                    JPContactos.removeAll();
                                }

                                JPContactos.revalidate();//NO MOVER DE AQUI
                                JPContactos.repaint();
                            }
                        } else {
                            String[] etqsE = new String[2];
                            etqsE[0] = d;
                            etqsE[1] = nom;

                            String[] etqsI = new String[2];
                            etqsI[0] = gpo;
                            etqsI[1] = nom;
                            VtnGrupo.r = Multilistas.mover(VtnGrupo.r, 0, etqsE, etqsI);

                            int pos = nom.toUpperCase().codePointAt(0) - 65;

                            if (VtnGrupo.arr.getArr()[pos] != null) {

                                ArbolBinario aba = new ArbolBinario();

                                NodoArbol aux = aba.busca(VtnGrupo.arr.getArr()[pos].getR(), nom);

                                if (aux != null) {

                                    aux.setPredecesores(etqsI);

                                    Propiedades p = new Propiedades(VtnGrupo.r, VtnGrupo.arr);
                                    try {
                                        Archivos.guardar(p, this);
                                    } catch (FileNotFoundException ex) {
                                        System.out.println(" No se encontro el archivo ");
                                    }
                                }
//
                            }
                            r1 = Multilistas.busca(VtnGrupo.r, d);
                            r1 = r1.getAbj();

                            if (r1 != null) {
                                Component componentes[] = JPContactos.getComponents();

                                for (int i = 0; i < componentes.length; i++) {
                                    System.out.println(((JButton) componentes[i]).getText());
                                    if (etqsE[1].equals(((JButton) componentes[i]).getText().trim())) {
                                        JPContactos.remove(i);
                                    }
                                }
                            } else {
                                JPContactos.removeAll();
                            }

                            JPContactos.revalidate();//NO MOVER DE AQUI
                            JPContactos.repaint();
                        }
                    }
                }

            }
        }/////////FIN DE VALIDA
        JPContactos.revalidate();
        JPContactos.repaint();
        System.out.println(Multilistas.desp(VtnGrupo.r, 0));
    }//GEN-LAST:event_jBMoverCActionPerformed

    private void jBEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarCActionPerformed

        String s = "";

        s = JOptionPane.showInputDialog("Escriba el nombre del contacto que desea eliminar");

        if (s == null) {
            //Evita el NPE al salir del showInputDialog o presionar cancelar
        } else if (valida(s) == false) {
            //Mensaje.error(this, "Debe rellenar el campo");
        } else {
            String[] etqs = new String[2];
            etqs[0] = d;
            etqs[1] = s;

            boolean c = false;

            if (cjb.ci.Mensaje.pregunta(this, "Eliminar contacto\nSe eliminaran las conversaciones "
                    + "asociadas a este contacto\n¿Desea continuar?") == 0) {
                c = true;
            }
            
            if (c==true) 
            {
                VtnGrupo.r = Multilistas.elimina(VtnGrupo.r, 0, etqs);

                int pos = s.toUpperCase().codePointAt(0) - 65;

                if (VtnGrupo.arr.getArr()[pos] != null) {

                    VtnGrupo.arr.elimina(s);

                    Propiedades p = new Propiedades(VtnGrupo.r, VtnGrupo.arr);

                    try {
                        Archivos.guardar(p, this);
                    } catch (FileNotFoundException ex) {
                        System.out.println("No se encontro el archivo");
                    }
                } else {
                    Mensaje.error(this, "No hay datos en esta posicion del arreglo");
                }
                
                //MOVI ESTO DENTRO DEL ELSE
                r1 = Multilistas.busca(VtnGrupo.r, d);
                r1 = r1.getAbj();

                if (r1 != null) {
                    Component componentes[] = JPContactos.getComponents();

                    for (int i = 0; i < componentes.length; i++) {
                        System.out.println(((JButton) componentes[i]).getText());
                        if (etqs[1].equals(((JButton) componentes[i]).getText().trim())) {
                            JPContactos.remove(i);
                        }
                    }
                } else {
                    JPContactos.removeAll();
                }
                //HASTA AQUI MOVI DENTRO DEL ELSE
            }

            //MOVI LO DE ARRIBA DE AQUI
            
        }
        JPContactos.updateUI();

        System.out.println(Multilistas.desp(VtnGrupo.r, 0));
    }//GEN-LAST:event_jBEliminarCActionPerformed

    private void jBRegresarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarCActionPerformed
        new VtnGrupo().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBRegresarCActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        r1 = Multilistas.busca(VtnGrupo.r, d);
        r1 = r1.getAbj();
        
        JPContactos.removeAll();
        
        if (r1 != null) {
            Nodo aux = r1;
            while (aux != null) {
                JButton boton = new JButton(aux.getEtq());

                boton.setBackground(Color.WHITE);//PONE EL FONDO DEL BOTON EN BLANCO
                boton.setForeground(Color.BLACK);//PONE LAS LETRAS COLOR NEGRO
                boton.setFont(new Font("arial", 1, 14));//CAMBIA LA FUENTE Y EL TAMAÑO

                //ESTABLECE UN TAMAÑO POR DEFECTO PARA LOS BOTONES
                boton.setMinimumSize(new Dimension(JPContactos.getWidth(), 50));
                boton.setMaximumSize(new Dimension(JPContactos.getWidth(), 50));
                boton.setPreferredSize(new Dimension(JPContactos.getWidth(), 50));

                JPContactos.add(boton);
                boton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        VtnHistorial h = new VtnHistorial();
                        h.d1 = d;
                        h.d2 = boton.getText();
                        h.setVisible(true);
                        dispose();
                    }
                }
                );
                aux = aux.getSig();
            }
        }

        JPContactos.revalidate();
        JPContactos.repaint();

    }//GEN-LAST:event_formWindowOpened

    private void jBAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsistenteActionPerformed
        JOptionPane.showMessageDialog(rootPane, "                                                     ¡Bienvenido a la ventana de contactos!\n"
                + "En esta ventana observaras los contactos que esten almacenados dentro del grupo que hayas ingresado\n"
                + "En esta ventana podras realizar distintas acciones como agregar o eliminar un contacto\n"
                + "Asi como buscar entre los distintos contactos que tengas y observar tu historial de chats");
    }//GEN-LAST:event_jBAsistenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPContactos;
    private javax.swing.JButton jBAgregarC;
    private javax.swing.JButton jBAsistente;
    private javax.swing.JButton jBEliminarC;
    private javax.swing.JButton jBMoverC;
    private javax.swing.JButton jBRegresarC;
    private javax.swing.JLabel jLAgregarC;
    private javax.swing.JLabel jLContactos;
    private javax.swing.JLabel jLEliminarC;
    private javax.swing.JLabel jLFondoC;
    private javax.swing.JLabel jLFondoC1;
    private javax.swing.JLabel jLMoverC;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
