/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.ArbolBinario;
import Clases.Archivos;
import Clases.Multilistas;
import Clases.Nodo;
import Clases.NodoArbol;
import Clases.Propiedades;
import static Vistas.VtnContacto.validaC;
import static Vistas.VtnGrupo.r;
import cjb.ci.Mensaje;
import java.awt.Component;
import java.io.FileNotFoundException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author zgame
 */
public class VtnMover extends javax.swing.JFrame {
    
    
        public boolean validaBE(String s) {
    boolean validabe = false;

        if (s.length() == 0) {
            Mensaje.error(this, "El campo se ecnuentra vacio, debe ingresar un nombre primero");
            validabe = false;
        } else {////////////////////////////////////////////////////////////prueba para evitar los mensajes de caracter no permitido en bus y elim
            if (s.length() > 30) {
                Mensaje.error(this, "El nombre que desea ingresar excede el numero de caracteres permitidos(30)");
                validabe = false;
            } else {
                validabe = true;
            }//fin del valida=30
        }//fin del valida s=0

        System.out.println("//////////////EL VALOR DE VALIDA ES " + validabe);
        return validabe;
    }

    public static boolean validaC(Nodo r, String etq)//valida que el nombre de un grupo no se repita 
    {
        boolean aux = false;
        while (r != null) {
            if (r.getEtq().equalsIgnoreCase(etq.trim())) {
                aux = true;
                break;
            } else {
                r = r.getSig();
            }
        }
        System.out.println("EL DATO QUE ENCONTRE FUE:" + aux);
        return aux;
    }

    public boolean validaE(String s)//valida que no haya espacios al principio y al final de la palabra
    {
        boolean validaE=false;
        
        char c=s.charAt(0);
        String p1=Character.toString(c);
        
        if (Character.isLetter(c)==false) 
        {
            Mensaje.error(this,"Caracter invalido detectado\nSolo se permiten letras");
            Mensaje.error(this,"Recuerde que no se permite el espacio al principio ni al final de una palabra");
            validaE=false;
        }
        else
        {
            validaE=true;
        }
        
        return validaE;
    }
    
    
    public String d; 
    String gpo="";
    String nom="";
    
    VtnGrupo g = new VtnGrupo();
    VtnContacto c = new VtnContacto();
    
    public VtnMover() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTMuestraContactos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMuestraGrupos = new javax.swing.JTextArea();
        jBMover = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBAceptarContacto = new javax.swing.JButton();
        jTContacto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jBAceptarGrupo = new javax.swing.JButton();
        jTGrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTMuestraContactos.setEditable(false);
        jTMuestraContactos.setColumns(20);
        jTMuestraContactos.setRows(5);
        jScrollPane1.setViewportView(jTMuestraContactos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 48, 330, 133));

        jLabel1.setText("Tus contactos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 25, -1, -1));

        jLabel2.setText("Tus grupos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 262, -1, -1));

        jTMuestraGrupos.setEditable(false);
        jTMuestraGrupos.setColumns(20);
        jTMuestraGrupos.setRows(5);
        jScrollPane2.setViewportView(jTMuestraGrupos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 285, 330, 135));

        jBMover.setText("Mover");
        jBMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMoverActionPerformed(evt);
            }
        });
        getContentPane().add(jBMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 522, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 522, -1, -1));

        jBAceptarContacto.setText("Aceptar");
        jBAceptarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarContactoActionPerformed(evt);
            }
        });
        getContentPane().add(jBAceptarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));
        getContentPane().add(jTContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 199, 150, -1));

        jLabel3.setText("Contacto que desea mover:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 202, 159, -1));

        jButton4.setText("Cancelar");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jBAceptarGrupo.setText("Aceptar");
        jBAceptarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(jBAceptarGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));
        getContentPane().add(jTGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 433, 170, -1));

        jLabel4.setText("Grupo al que desea mover:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 436, -1, -1));

        jButton6.setText("Cancelar");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondomover12.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarContactoActionPerformed
        nom=jTContacto.getText();
    }//GEN-LAST:event_jBAceptarContactoActionPerformed

    private void jBMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMoverActionPerformed
        Nodo rm;

        boolean b1 = true;
        boolean b2 = true;
        
        nom=jTContacto.getText();
        if (nom == null) 
        {
            b1 = false;
            //Evita el NPE al salir del showInputDialog o presionar cancelar
        } else 
            if (validaBE(nom) != false) ///////////////////////////////////////prueba de valida
            {
                if (validaE(nom)==false) 
                {
                    System.out.println("");
                }
                else
                {
                    gpo=jTGrupo.getText();
                    //gpo = JOptionPane.showInputDialog("Escriba el grupo al que desea mover este contacto");
                if (gpo != null) //Evita el NPE al salir del showInputDialog o presionar cancelar
                {
                b2 = false;
                    if (validaE(gpo)==false)//valida que no haya espacios al principio
                    {
                        System.out.println("");
                    }
                    else
                    {
                        
                        if (validaC(g.r, gpo) == false)//significa que no encontro nada 
                        {
                            Mensaje.error(this, "El grupo al cual desea mover el contacto no se encontro");
                        } 
                        else 
                        {

                            if (gpo.length() == 0) {
                                Mensaje.error(this, "Los campos no deben estar vacios");
                            }
                            if (b1 == false && b2 == false) {

                            } else if (nom.length() != 0 && gpo.length() != 0) {
                                rm = Multilistas.busca(VtnGrupo.r, gpo);
                                rm = rm.getAbj();

                                if (rm != null) {
                                    if (validaC(rm, nom) == true) {
                                        Mensaje.error(this, "El nombre que intentas ingresar esta repetido en grupo " + gpo);
                                    } else {
                                        String[] etqsE = new String[2];
                                        etqsE[0] = d;
                                        etqsE[1] = nom;

                                        String nom2 = nom.toUpperCase().charAt(0) + nom.substring(1, nom.length());
                                        String[] etqsI = new String[2];
                                        etqsI[0] = gpo;
                                        etqsI[1] = nom2;

                                        VtnGrupo.r = Multilistas.mover(VtnGrupo.r, 0, etqsE, etqsI);

                                        int pos = nom.toUpperCase().codePointAt(0) - 65;

                                        if (VtnGrupo.arr.getArr()[pos] != null) {

                                            ArbolBinario aba = new ArbolBinario();

                                            NodoArbol aux = aba.busca(VtnGrupo.arr.getArr()[pos].getR(), nom);

                                            if (aux != null) {

                                                aux.setPredecesores(etqsI);
                                                String muestra[] = aux.getPredecesores();

                                                System.out.println("Etqs modificada " + muestra[0]);
                                                System.out.println("Etqs modificadas " + muestra[1]);

                                                Propiedades p = new Propiedades(VtnGrupo.r, VtnGrupo.arr);
                                                try {
                                                    Archivos.guardar(p, this);
                                                } catch (FileNotFoundException ex) {
                                                    System.out.println(" No se encontro el archivo ");
                                                }
                                            }
                                        }
                                        c.r1 = Multilistas.busca(VtnGrupo.r, d);
                                        c.r1 = c.r1.getAbj();

                                        if (c.r1 != null) {
                                            Component componentes[] = VtnContacto.JPContactos.getComponents();

                                            for (int i = 0; i < componentes.length; i++) {
                                                System.out.println(((JButton) componentes[i]).getText());
                                                if (etqsE[1].trim().equalsIgnoreCase(((JButton) componentes[i]).getText().trim())) {
                                                    VtnContacto.JPContactos.remove(i);
                                                }
                                            }

                                        } else {
                                            VtnContacto.JPContactos.removeAll();
                                        }

                                        VtnContacto.JPContactos.revalidate();//NO MOVER DE AQUI
                                        VtnContacto.JPContactos.repaint();
                                    }
                                } else {
                                    String[] etqsE = new String[2];
                                    etqsE[0] = d;
                                    etqsE[1] = nom;

                                    String nom2 = nom.toUpperCase().charAt(0) + nom.substring(1, nom.length());
                                    String[] etqsI = new String[2];
                                    etqsI[0] = gpo;
                                    etqsI[1] = nom2;
                                    VtnGrupo.r = Multilistas.mover(VtnGrupo.r, 0, etqsE, etqsI);

                                    int pos = nom.toUpperCase().codePointAt(0) - 65;

                                    if (VtnGrupo.arr.getArr()[pos] != null) {

                                        ArbolBinario aba = new ArbolBinario();

                                        NodoArbol aux = aba.busca(VtnGrupo.arr.getArr()[pos].getR(), nom);

                                        if (aux != null) {

                                            aux.setPredecesores(etqsI);

                                            String muestra[] = aux.getPredecesores();

                                            System.out.println("Etqs modificada " + muestra[0]);
                                            System.out.println("Etqs modificadas " + muestra[1]);

                                            Propiedades p = new Propiedades(VtnGrupo.r, VtnGrupo.arr);
                                            try {
                                                Archivos.guardar(p, this);
                                            } catch (FileNotFoundException ex) {
                                                System.out.println(" No se encontro el archivo ");
                                            }
                                        }
        //
                                    }
                                    c.r1 = Multilistas.busca(VtnGrupo.r, d);
                                    c.r1 = c.r1.getAbj();

                                    if (c.r1 != null) {
                                        Component componentes[] = VtnContacto.JPContactos.getComponents();

                                        for (int i = 0; i < componentes.length; i++) {
                                            System.out.println(((JButton) componentes[i]).getText());
                                            if (etqsE[1].trim().equalsIgnoreCase(((JButton) componentes[i]).getText().trim())) {
                                                VtnContacto.JPContactos.remove(i);
                                            }
                                        }
                                    } else {
                                        VtnContacto.JPContactos.removeAll();
                                    }

                                    VtnContacto.JPContactos.revalidate();//NO MOVER DE AQUI
                                    VtnContacto.JPContactos.repaint();
                                }
                            }
                        }
                        
                        
                    }//fin del validaE de grupo
            }//fin del gpo!=null
        }/////////FIN DE VALIDA
    }//fin del validaE
        
        VtnContacto.JPContactos.revalidate();//NO MOVER DE AQUI
        VtnContacto.JPContactos.repaint();
        
    }//GEN-LAST:event_jBMoverActionPerformed

    private void jBAceptarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarGrupoActionPerformed
        gpo=jTGrupo.getText();
    }//GEN-LAST:event_jBAceptarGrupoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         VtnGrupo g = new VtnGrupo();
        
        String s = "";

        while (g.r != null) 
        {
            s += "*" + g.r.getEtq() + "\n";
            g.r = g.r.getSig();

        }
        
        jTMuestraGrupos.setText(s);
        
        /*c.r1 = Multilistas.busca(VtnGrupo.r, d);
        c.r1 = c.r1.getAbj();
        
        String t = "";

        while (g.r != null) 
        {
            t += "*" + c.r1.getEtq() + "\n";
            c.r1 = c.r1.getSig();

        }
        
        jTMuestraGrupos.setText(t);*/
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnMover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnMover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnMover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnMover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnMover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarContacto;
    private javax.swing.JButton jBAceptarGrupo;
    private javax.swing.JButton jBMover;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTContacto;
    private javax.swing.JTextField jTGrupo;
    private javax.swing.JTextArea jTMuestraContactos;
    private javax.swing.JTextArea jTMuestraGrupos;
    // End of variables declaration//GEN-END:variables
}
