/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.ColaDinamica;
import Clases.Nodo;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;

/**
 *
 * @author josea
 */
public class vtnBusca extends javax.swing.JFrame {

    /**
     * Creates new form vtnBusca
     */
    public vtnBusca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBusca = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfBusca = new javax.swing.JTextField();
        btnBuscaChat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpFondo2.setBackground(new java.awt.Color(255, 255, 255));
        jpFondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taBusca.setColumns(20);
        taBusca.setRows(5);
        jScrollPane1.setViewportView(taBusca);

        jpFondo2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 401, 190));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa la frase o palabra a buscar");
        jpFondo2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 212, 27));

        tfBusca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscaActionPerformed(evt);
            }
        });
        tfBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscaKeyTyped(evt);
            }
        });
        jpFondo2.add(tfBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 183, -1));

        btnBuscaChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/aceptar-esquema-de-boton-circular.png"))); // NOI18N
        btnBuscaChat.setBorderPainted(false);
        btnBuscaChat.setContentAreaFilled(false);
        btnBuscaChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaChatActionPerformed(evt);
            }
        });
        btnBuscaChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscaChatKeyPressed(evt);
            }
        });
        jpFondo2.add(btnBuscaChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 53, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoarribabusca.jpg"))); // NOI18N
        jpFondo2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoBusca.jpg"))); // NOI18N
        jLFondo.setText("jLabel2");
        jpFondo2.add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        getContentPane().add(jpFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscaChatKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            btnBuscaChatActionPerformed(null);
        }
        CtrlInterfaz.limpia(tfBusca);
    }//GEN-LAST:event_btnBuscaChatKeyPressed

    private void btnBuscaChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaChatActionPerformed
        // TODO add your handling code here:
        int bandera = 0;
        ColaDinamica cdt = new ColaDinamica();
        Nodo aux = null;
        String sb = "";

        while (vtnChat.cd.getFrente()!= null) {
            aux = vtnChat.cd.Elimina();
            if (aux.getObj().toString().toLowerCase().contains(tfBusca.getText().toLowerCase())) {
                sb += aux.getObj().toString() + "\n";
                bandera = 1;
            } else 
            {
                //
                if (vtnChat.cd.getFrente()== null && bandera == 0) {
                    Mensaje.error(this, "Dato no encontrado");
                }
            }            
            cdt.Inserta(aux);
        }
        vtnChat.cd = cdt;
        taBusca.setText(sb);        
    }//GEN-LAST:event_btnBuscaChatActionPerformed

    private void tfBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscaKeyTyped
        // TODO add your handling code here:
        if (tfBusca.getText().length() == 9) {
            evt.consume();
        }

    }//GEN-LAST:event_tfBuscaKeyTyped

    private void tfBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscaKeyPressed
        // TODO add your handling code here:
        Validaciones.enter(this, evt, btnBuscaChat);
    }//GEN-LAST:event_tfBuscaKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (vtnChat.cd.getFrente()== null) {
            tfBusca.setEditable(false);
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void tfBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnBusca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaChat;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpFondo2;
    private javax.swing.JTextArea taBusca;
    private javax.swing.JTextField tfBusca;
    // End of variables declaration//GEN-END:variables
}
