/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.ColaDinamica;
import Clases.Nodo;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;

/**
 *
 * @author josea
 */
public class vtnBusca extends javax.swing.JFrame {

    /**
     * Creates new form vtnBusca
     */
    public vtnBusca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBusca = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfBusca = new javax.swing.JTextField();
        btnBuscaChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpFondo2.setBackground(new java.awt.Color(255, 204, 255));

        taBusca.setBackground(new java.awt.Color(204, 255, 204));
        taBusca.setColumns(20);
        taBusca.setRows(5);
        jScrollPane1.setViewportView(taBusca);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 3, 12)); // NOI18N
        jLabel1.setText("Ingresa la frase o palabra a buscar");

        tfBusca.setBackground(new java.awt.Color(204, 204, 255));
        tfBusca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscaActionPerformed(evt);
            }
        });
        tfBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscaKeyTyped(evt);
            }
        });

        btnBuscaChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/aceptar-esquema-de-boton-circular.png"))); // NOI18N
        btnBuscaChat.setBorderPainted(false);
        btnBuscaChat.setContentAreaFilled(false);
        btnBuscaChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaChatActionPerformed(evt);
            }
        });
        btnBuscaChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscaChatKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpFondo2Layout = new javax.swing.GroupLayout(jpFondo2);
        jpFondo2.setLayout(jpFondo2Layout);
        jpFondo2Layout.setHorizontalGroup(
            jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpFondo2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpFondo2Layout.createSequentialGroup()
                            .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBuscaChat))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(176, Short.MAX_VALUE)))
        );
        jpFondo2Layout.setVerticalGroup(
            jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondo2Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpFondo2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBuscaChat)
                        .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(217, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscaChatKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            btnBuscaChatActionPerformed(null);
        }
        CtrlInterfaz.limpia(tfBusca);
    }//GEN-LAST:event_btnBuscaChatKeyPressed

    private void btnBuscaChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaChatActionPerformed
        // TODO add your handling code here:
        int bandera = 0;
        ColaDinamica cdt = new ColaDinamica();
        Nodo aux = null;
        String sb = "";

        while (vtnChat.cd.getFrente()!= null) {
            aux = vtnChat.cd.Elimina();
            if (aux.getObj().toString().toLowerCase().contains(tfBusca.getText().toLowerCase())) {
                sb += aux.getObj().toString() + "\n";
                bandera = 1;
            } else 
            {
                //
                if (vtnChat.cd.getFrente()== null && bandera == 0) {
                    Mensaje.error(this, "Dato no encontrado");
                }
            }            
            cdt.Inserta(aux);
        }
        vtnChat.cd = cdt;
        taBusca.setText(sb);        
    }//GEN-LAST:event_btnBuscaChatActionPerformed

    private void tfBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscaKeyTyped
        // TODO add your handling code here:
        if (tfBusca.getText().length() == 9) {
            evt.consume();
        }

    }//GEN-LAST:event_tfBuscaKeyTyped

    private void tfBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscaKeyPressed
        // TODO add your handling code here:
        Validaciones.enter(this, evt, btnBuscaChat);
    }//GEN-LAST:event_tfBuscaKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (vtnChat.cd.getFrente()== null) {
            tfBusca.setEditable(false);
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void tfBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnBusca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaChat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpFondo2;
    private javax.swing.JTextArea taBusca;
    private javax.swing.JTextField tfBusca;
    // End of variables declaration//GEN-END:variables
}
