/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Multilistas;
import Clases.Nodo;
import cjb.ci.Mensaje;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author zgame
 */
public class VtnContacto extends javax.swing.JFrame {

    public String d;
    public Nodo r1;

    /**
     * Creates new form VtnContacto
     */
    public VtnContacto() {
        initComponents();
        this.setLocationRelativeTo(null); //CENTRA LA PANTALLA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLContactos = new javax.swing.JLabel();
        jBAgregarC = new javax.swing.JButton();
        jBEliminarC = new javax.swing.JButton();
        jBRegresarC = new javax.swing.JButton();
        jBMoverC = new javax.swing.JButton();
        jLRegresarC = new javax.swing.JLabel();
        jLEliminarC = new javax.swing.JLabel();
        jLMoverC = new javax.swing.JLabel();
        jLAgregarC = new javax.swing.JLabel();
        JPContactos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLContactos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLContactos.setText("Contactos");

        jBAgregarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar50.jpg"))); // NOI18N
        jBAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarCActionPerformed(evt);
            }
        });

        jBEliminarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/elimina50.jpg"))); // NOI18N
        jBEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarCActionPerformed(evt);
            }
        });

        jBRegresarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresa.jpg"))); // NOI18N
        jBRegresarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarCActionPerformed(evt);
            }
        });

        jBMoverC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/moverc.jpg"))); // NOI18N
        jBMoverC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMoverCActionPerformed(evt);
            }
        });

        jLRegresarC.setText("Regresar");

        jLEliminarC.setText("Eliminar");

        jLMoverC.setText("Mover");

        jLAgregarC.setText("Agregar");

        JPContactos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPContactos.setLayout(new java.awt.GridLayout(0, 1, 0, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLContactos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBRegresarC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLRegresarC))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEliminarC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBMoverC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLMoverC)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLAgregarC))
                            .addComponent(jBAgregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(56, Short.MAX_VALUE)
                    .addComponent(JPContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLContactos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBRegresarC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLRegresarC)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAgregarC)
                            .addComponent(jBMoverC)
                            .addComponent(jBEliminarC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEliminarC)
                            .addComponent(jLMoverC)
                            .addComponent(jLAgregarC))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(JPContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarCActionPerformed

        System.out.println(d);

        String s = "";
        s = JOptionPane.showInputDialog("Escriba el nombre del contacto que desea agregar");
        if (s.length() == 0) {
            Mensaje.error(this, "Debe rellenar el campo");
        }
        if (s.length() != 0) {
            Nodo con = new Nodo(null, s);
            String[] etqs = new String[2];
            etqs[0] = d;//toma el texto del boton que se eligio anteriorente
            etqs[1] = s;
            VtnGrupo.r = Multilistas.inserta(VtnGrupo.r, con, 0, etqs); //elimina

            r1 = Multilistas.busca(VtnGrupo.r, d); //buscar en donde vas a insertar
            r1 = r1.getAbj();//si
            JPContactos.removeAll();
            if (r1 != null) {
                Nodo aux = r1;
                while (aux != null) {
                    JButton boton = new JButton(aux.getEtq());
                    JPContactos.add(boton);
                    boton.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            VtnHistorial h = new VtnHistorial();
                            h.d1 = d;
                            h.d2 = boton.getText();
                            h.setVisible(true);
                        }
                    }
                    );
                    aux = aux.getSig();
                }
            }

            JPContactos.revalidate();
            JPContactos.repaint();

        }
    }//GEN-LAST:event_jBAgregarCActionPerformed

    private void jBMoverCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMoverCActionPerformed

        String nom = ""; //nom=NOMBRE A BUSCAR
        String gpo = "";

        nom = JOptionPane.showInputDialog("Escriba el contacto que desea buscar");
        if (nom.length() == 0) {
            Mensaje.error(this, "Los campos no deben estar vacios");
        }
        gpo = JOptionPane.showInputDialog("Escriba el grupo al que desea mover este contacto");
        if (gpo.length() == 0) {
            Mensaje.error(this, "Los campos no deben estar vacios");
        }
        if (nom.length() != 0 && gpo.length() != 0) {
            String[] etqsE = new String[2];
            etqsE[0] = d;
            etqsE[1] = nom;

            String[] etqsI = new String[2];
            etqsI[0] = gpo;
            etqsI[1] = nom;

            VtnGrupo.r = Multilistas.mover(VtnGrupo.r, 0, etqsE, etqsI);

            System.out.println(Multilistas.desp(VtnGrupo.r, 0));

        }

    }//GEN-LAST:event_jBMoverCActionPerformed

    private void jBEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarCActionPerformed

        String s = "";

        s = JOptionPane.showInputDialog("Escriba el nombre del contacto que desea eliminar");
        if (s.length() == 0) {
            Mensaje.error(this, "Debe rellenar el campo");
        }
        if (s.length() != 0) {
            Nodo con = new Nodo(null, s);
            String[] etqs = new String[2];
            etqs[0] = d;
            etqs[1] = s;

            boolean c = false;

            if (cjb.ci.Mensaje.pregunta(this, "Eliminar grupo\nSe eliminaran los contactos "
                    + "y conversaciones asociados a este grupo\n¿Continuar?") == 0) {
                c = true;
            }

            if (c) {
                VtnGrupo.r = Multilistas.elimina(VtnGrupo.r, 0, etqs);
            }

            r1 = Multilistas.busca(VtnGrupo.r, d);
            r1 = r1.getAbj();
//            JPContactos.removeAll();
            if (r1 != null) {
                Nodo aux = r1;
                while (aux != null) {
                    JButton boton = new JButton(aux.getEtq());
                    System.out.println("Etiqueta en aux " + aux.getEtq());
                    Component componentes[] = JPContactos.getComponents();

                    for (int i = 0; i < componentes.length; i++) {
                        System.out.println(((JButton) componentes[i]).getText());
                        if (etqs[1].equals(((JButton) componentes[i]).getText().trim())) {
                            JPContactos.remove(i);
                        }
                    }
                    boton.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            VtnHistorial h = new VtnHistorial();
                            h.d1 = d;
                            h.d2 = boton.getText();
                            h.setVisible(true);
                        }
                    }
                    );
                    aux = aux.getSig();
                }
            }

            if (c) {
                JPContactos.revalidate();
                JPContactos.repaint();
            }

        }
        System.out.println(Multilistas.desp(VtnGrupo.r, 0));
    }//GEN-LAST:event_jBEliminarCActionPerformed

    private void jBRegresarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarCActionPerformed
        new VtnGrupo().setVisible(true);
        dispose();
        //this.setVisible(false);
    }//GEN-LAST:event_jBRegresarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPContactos;
    private javax.swing.JButton jBAgregarC;
    private javax.swing.JButton jBEliminarC;
    private javax.swing.JButton jBMoverC;
    private javax.swing.JButton jBRegresarC;
    private javax.swing.JLabel jLAgregarC;
    private javax.swing.JLabel jLContactos;
    private javax.swing.JLabel jLEliminarC;
    private javax.swing.JLabel jLMoverC;
    private javax.swing.JLabel jLRegresarC;
    // End of variables declaration//GEN-END:variables
}
