package Vistas;

import Clases.ColasD;
import Clases.Nodo;
import Clases.PilasD;
import Clases.Propiedades;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author zgame
 */
public class VtnW extends javax.swing.JFrame {

    //OBJETO QUE ALMACENARA 
    Propiedades obj = new Propiedades();

    private PilasD p1 = new PilasD();
    private PilasD p2 = new PilasD();
    private ColasD c = new ColasD();

    String s = "";
    
    public Nodo raiz;

    public String d1;
    public String d2;
    public String d3;

    public VtnW() {
        initComponents();
        this.setLocationRelativeTo(null);//CENTRA LA PANTALLA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBEnviar1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTConversacion = new javax.swing.JTextArea();
        jTChat1 = new javax.swing.JTextField();
        jTChat2 = new javax.swing.JTextField();
        jBEnviar2 = new javax.swing.JButton();
        jBOrdenar1 = new javax.swing.JButton();
        jBOrdenar2 = new javax.swing.JButton();
        jBBuscar1 = new javax.swing.JButton();
        jBBuscar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBMostrarTexto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLRegresar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBOrdenaC = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jBEnviar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enviarw.png"))); // NOI18N
        jBEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviar1ActionPerformed(evt);
            }
        });

        jTConversacion.setEditable(false);
        jTConversacion.setColumns(20);
        jTConversacion.setRows(5);
        jScrollPane3.setViewportView(jTConversacion);

        jTChat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTChat1ActionPerformed(evt);
            }
        });
        jTChat1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTChat1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTChat1KeyTyped(evt);
            }
        });

        jTChat2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTChat2KeyPressed(evt);
            }
        });

        jBEnviar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enviarw.png"))); // NOI18N
        jBEnviar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviar2ActionPerformed(evt);
            }
        });

        jBOrdenar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ordenar50.png"))); // NOI18N
        jBOrdenar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrdenar1ActionPerformed(evt);
            }
        });

        jBOrdenar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ordenar50.png"))); // NOI18N
        jBOrdenar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrdenar2ActionPerformed(evt);
            }
        });

        jBBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar50.png"))); // NOI18N
        jBBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscar1ActionPerformed(evt);
            }
        });

        jBBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar50.png"))); // NOI18N
        jBBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscar2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar");

        jLabel2.setText("Ordenar");

        jLabel3.setText("Buscar");

        jLabel4.setText("Ordenar");

        jBMostrarTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/conversacion.png"))); // NOI18N
        jBMostrarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarTextoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Chat principal");

        jLabel6.setText("Persona 2");

        jLRegresar.setText("Chat principal");

        jLabel7.setText("Persona 1");

        jBOrdenaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ordenar50.png"))); // NOI18N
        jBOrdenaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrdenaCActionPerformed(evt);
            }
        });

        jLabel8.setText("Ordenar Chat");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresa.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jBOrdenar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTChat1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBEnviar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLabel2))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jBOrdenar2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(15, 15, 15))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jBOrdenaC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jBMostrarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jTChat2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel6)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTChat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jTChat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBOrdenar2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBEnviar2)
                                    .addComponent(jBBuscar2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBMostrarTexto)
                                        .addGap(9, 9, 9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBOrdenaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBBuscar1)
                                    .addComponent(jBOrdenar1)
                                    .addComponent(jBEnviar1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTChat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTChat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTChat1ActionPerformed

    private void jTChat1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTChat1KeyPressed

    }//GEN-LAST:event_jTChat1KeyPressed

    private void jTChat2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTChat2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTChat2KeyPressed

    private void jBEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviar1ActionPerformed

        //EN ESTA PARTE SE DEBE MANDAR EL TEXTO A LA PILA 1
        if (jTChat1.getText().length() == 0) {
            Mensaje.error(this, "Mensaje vacio"); //ENVIA UN MENSAJE DE ERROR EN CASO DE QUE NO HAYA ESCRITO NADA
        } else {
            Nodo n = new Nodo(jTChat1.getText());

            p1.inserta(n);
            c.inserta(n);
            obj.setNum(obj.getNum() + 1);
            CtrlInterfaz.limpia(jTChat1); //LIMPIA LA CAJA DE TEXTO
            muestra();
        }
    }//GEN-LAST:event_jBEnviar1ActionPerformed

    private void jBEnviar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviar2ActionPerformed

        //EN ESTA PARTE SE DEBE MANDAR EL TEXTO A LA PILA 2
        if (jTChat2.getText().length() == 0) 
        {
            Mensaje.error(this, "Mensaje vacio");
        } else 
        {
            Nodo n = new Nodo("                               " + "                               " + jTChat2.getText());
            p2.inserta(n);
            c.inserta(n);
            obj.setNum(obj.getNum() + 1);
            CtrlInterfaz.limpia(jTChat2);
            muestra();

        }
    }//GEN-LAST:event_jBEnviar2ActionPerformed

    private void jBBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscar1ActionPerformed
        buscare(p1);
    }//GEN-LAST:event_jBBuscar1ActionPerformed

    private void jBOrdenar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrdenar1ActionPerformed
        ordena(p1);
    }//GEN-LAST:event_jBOrdenar1ActionPerformed

    private void jBOrdenar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrdenar2ActionPerformed
        ordena(p2);
    }//GEN-LAST:event_jBOrdenar2ActionPerformed

    private void jBBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscar2ActionPerformed
        buscare(p2);
    }//GEN-LAST:event_jBBuscar2ActionPerformed

    private void jBMostrarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarTextoActionPerformed
        muestra();
    }//GEN-LAST:event_jBMostrarTextoActionPerformed

    private void jBOrdenaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrdenaCActionPerformed
        ordenac(c);
    }//GEN-LAST:event_jBOrdenaCActionPerformed

    private void jTChat1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTChat1KeyTyped

    }//GEN-LAST:event_jTChat1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new VtnHistorial().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    public void buscar(PilasD p)
    {
        
        Object busca=JOptionPane.showInputDialog(null, "Dato a buscar:");
        
        boolean bandera=false;
        Object encontrado=null;
        
        PilasD auxiliar = new PilasD();

        for (int i = 0; i < obj.getNum(); i++)
        {
            try
            {
                Nodo aux = new Nodo(p.elimina().getObj());
                auxiliar.inserta(aux);
            } catch (NullPointerException ex)
            {
                break;
            }
        }

        while ( auxiliar.getTope()!=null) 
        {
            if (auxiliar.busca(busca)!=null) 
            {
                encontrado=auxiliar.getTope();
                //JOptionPane.showMessageDialog(null, "Dato encontrado: "+p.getTope().getObj());
                jTConversacion.setText("DATO ENCONTRADO: "+(String)auxiliar.getTope().getObj());
                auxiliar.setTope(null);
                bandera=true;
                //break;
            }
        }
        if (bandera==false) 
        {
            JOptionPane.showMessageDialog(null, "No se encontro ningun dato");
        }   
    }
    
    public void buscare(PilasD p)
    {
        int n=0;
        String arrr[];
        boolean bandera=false;
        int i;
        
        if(p==null)
        {
            System.out.println("LA PILA ESTA VACIA");
        }
        else
        {   
            PilasD auxiliar = new PilasD();

            for (i = 0; i < obj.getNum(); i++)
            {
                try
                {
                    Nodo aux = new Nodo(p.elimina().getObj());
                    auxiliar.inserta(aux);
                    n=n+1;
                } catch (NullPointerException ex)
                {
                    break;
                }
            }
            
            arrr = new String[n];

            for (i = 0; i < n; i++)
            {
                try
                {
                    Nodo aux = new Nodo(auxiliar.elimina().getObj());
                    p.inserta(aux);
                    arrr[i] = (String) aux.getObj();
                } catch (NullPointerException ex)
                {
                    break;
                }
            }
            
            /*int x=si.length;
            System.out.println(x);
         
            /*for (i = 0; i < si.length; i++) 
            {
                System.out.println("DATO INGRESADO EN LA POSICION ["+ i +"]"+"=" + si[i]);
            }*/
            
            //System.out.println("NUMERO DE DATOS INGRESADOS: "+n);
            
            String buscar=JOptionPane.showInputDialog(null,"Ingrese dato a buscar");
            
            //System.out.println("CADENA A BUSCAR: "+buscar);
            
            //int acum=0;
            
            for (i = 0; i < arrr.length; i++) 
            {
                if (arrr[i].compareTo(buscar)==0)//NO ENTRA EN El CICLO 
                {
                    //jTConversacion.setText("DATO ENCONTRADo: "+ auxiliar.elimina().getObj());
                    
                    
                    //Mensaje.exito(this,"DATO ENCONTRADO: "+ si[i]);
                    bandera=true;
                    //System.out.println("VALOR DE BANDERA DENTRO DEL FOR"+bandera);
                    //break;
                    //acum=acum+1;
                    break;
                }
            }
            
            
            //System.out.println("VALOR DE i:"+i);
            
            //System.out.println("VALOR DE BANDERA FUERA DEL FOR"+bandera);
            
            if (bandera==false) 
            {
                Mensaje.error(this,"DATO NO ENCONTRADO");
            }
            else
            {
                
                Mensaje.exito(this,"DATO ENCONTRADO: "+ arrr[i]);
            }
            
            buscar="";
            
            //System.out.println("VALOR LIMPIO:"+buscar);
            
        }
    }
    
    public void muestra() //METODO QUE MUESTRA LOS DATOS DE LA PILA EN EL CHAT PRINCIPAL
    {
        s = "";

        ColasD cmuestra = new ColasD(); //DECLARA UNA COLA AUXILIAR LA CUAL CONTENDRA LOS DATOS A MOSTRAR EN EL CHAT

        for (int i = 0; i < obj.getNum(); i++) //FOR QUE RECORRE TODOS LOS DATOS QUE TIENE LA COLA
        {

            Nodo aux = new Nodo(c.elimina().getObj());//CREA UN NODO PARA CADA OBJETO DE LA COLA

            if (aux == null) //SI LA COLA ESTA VACIA DETIENE EL CICLO
            {
                break;
            }

            cmuestra.inserta(aux);//INSERTA CADA DATO EN UN NODO
            s += " " + String.valueOf(aux.getObj()) + "\n"; //OBTIENE EL VALOR DE INTERNO DE CADA OBJETO DEL NODO
        }

        jTConversacion.setText(s);

        for (int i = 0; i < obj.getNum(); i++) {
            Nodo aux = new Nodo(cmuestra.elimina().getObj());
            c.inserta(aux);
        }
    }
  
    public void ordenac (ColasD c)//METODO QUE ORDENA LOS DATOS DE LA COLA
    {
        String m = "";//Mensaje
        String arr[];//Arreglo
        int n = 0;//Numeroo datos
        ColasD a = new ColasD();

        for (int i = 0; i < obj.getNum(); i++) //OBTIENE EL NUMERO DE DATOS DE LA COLA
        {
            try {
                Nodo aux = new Nodo(c.elimina().getObj());
                a.inserta(aux);
                n += 1;
            } catch (NullPointerException ex) {
                break;
            }
        }

        arr = new String[n];//DECLARA UN ARREGLO CON EL NUMERO DE DATOS QUE TIENE EL OBJETO

        for (int i = 0; i < n; i++)//FOR QUE INSERTA EN EL ARREGLO LOS DATOS
        {
            try {
                Nodo aux = new Nodo(a.elimina().getObj());
                c.inserta(aux);
                arr[i] = (String) aux.getObj();
            } catch (NullPointerException ex) {
                break;
            }
        }

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - 1; j++) {
                if (arr[j].compareTo(arr[j + 1]) > 0) //compareTo METODO QUE COMPARA DOS CADENAS
                {
                    String tmp = arr[j + 1];
                    arr[j + 1] = arr[j];
                    arr[j] = tmp;
                }
            }
        }
        
        for (int i = 0; i < n; i++) {
            System.out.println(arr[i]);
            m += arr[i] + "\n";
        }

        jTConversacion.setText(m);
    }
    
    
    public void ordena(PilasD p) //METODO QUE ORDENA LOS DATOS DE UNA PILA
    {

        String t = "";//texto
        String ar[];//
        int n = 0;
        PilasD auxiliar = new PilasD();

        for (int i = 0; i < obj.getNum(); i++) //OBTIENE EL NUMERO DE DATOS DE LA COLA
        {
            try {
                Nodo aux = new Nodo(p.elimina().getObj());
                auxiliar.inserta(aux);
                n += 1;
            } catch (NullPointerException ex) {
                break;
            }
        }

        ar = new String[n];//DECLARA UN ARREGLO CON EL NUMERO DE DATOS QUE TIENE EL OBJETO

        for (int i = 0; i < n; i++)//FOR QUE INSERTA EN EL ARREGLO LOS DATOS
        {
            try {
                Nodo aux = new Nodo(auxiliar.elimina().getObj());
                p.inserta(aux);
                ar[i] = (String) aux.getObj();
            } catch (NullPointerException ex) {
                break;
            }
        }

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - 1; j++) {
                if (ar[j].compareTo(ar[j + 1]) > 0) {
                    String tmp = ar[j + 1];
                    ar[j + 1] = ar[j];
                    ar[j] = tmp;
                }
            }
        }
        
        for (int i = 0; i < n; i++) {
            System.out.println(ar[i]);
            t += ar[i] + "\n";
        }

        jTConversacion.setText(t);
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar1;
    private javax.swing.JButton jBBuscar2;
    private javax.swing.JButton jBEnviar1;
    private javax.swing.JButton jBEnviar2;
    private javax.swing.JButton jBMostrarTexto;
    private javax.swing.JButton jBOrdenaC;
    private javax.swing.JButton jBOrdenar1;
    private javax.swing.JButton jBOrdenar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTChat1;
    private javax.swing.JTextField jTChat2;
    private javax.swing.JTextArea jTConversacion;
    // End of variables declaration//GEN-END:variables
}
